import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import request from 'supertest';
import app from '../server.js';
import Listing from '../models/Listing.js';
import { connectDB, disconnectDB, clearDB, createTestUser, createTestAdmin } from './setup.js';

process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-secret-key';
process.env.NODE_ENV = 'test';

let userToken, userId, adminToken;

beforeAll(async () => await connectDB());
afterAll(async () => await disconnectDB());

beforeEach(async () => {
  await clearDB();

  const user = await createTestUser({ email: 'seller@techpulse.com' });
  const admin = await createTestAdmin();
  userToken = user.token;
  userId = user.user._id;
  adminToken = admin.token;
});

// Helper — create listing directly in DB (bypasses Cloudinary upload)
const createSampleListing = async (overrides = {}) => {
  return Listing.create({
    seller: userId,
    title: 'iPhone 14 Pro Max',
    category: 'Smartphone',
    price: 850,
    condition: 'Très bon état',
    description: 'iPhone 14 Pro Max 256Go, très bon état, toujours sous garantie Apple.',
    images: [
      { url: 'https://res.cloudinary.com/demo/image/upload/photo1.jpg', publicId: 'photo1' },
      { url: 'https://res.cloudinary.com/demo/image/upload/photo2.jpg', publicId: 'photo2' },
      { url: 'https://res.cloudinary.com/demo/image/upload/photo3.jpg', publicId: 'photo3' },
    ],
    video: {
      url: 'https://res.cloudinary.com/demo/video/upload/demo.mp4',
      publicId: 'demo-video',
      duration: 30,
    },
    status: 'pending',
    ...overrides,
  });
};

describe('Listings API', () => {
  // ── GET /api/listings ──
  describe('GET /api/listings', () => {
    it('should return only active listings', async () => {
      await createSampleListing({ status: 'active', title: 'Active iPhone' });
      await createSampleListing({ status: 'pending', title: 'Pending Galaxy' });
      await createSampleListing({ status: 'rejected', title: 'Rejected Pixel' });

      const res = await request(app).get('/api/listings');

      expect(res.status).toBe(200);
      const listings = res.body.listings || res.body;
      expect(listings.length).toBe(1);
      expect(listings[0].title).toBe('Active iPhone');
    });

    it('should be accessible without auth', async () => {
      const res = await request(app).get('/api/listings');
      expect(res.status).toBe(200);
    });
  });

  // ── GET /api/listings/:slug ──
  describe('GET /api/listings/:slug', () => {
    it('should return a listing by slug', async () => {
      const listing = await createSampleListing({ status: 'active' });

      // Slug is auto-generated by pre('save'), use the one from DB
      const res = await request(app).get(`/api/listings/${listing.slug}`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty('title', 'iPhone 14 Pro Max');
      expect(res.body).toHaveProperty('images');
      expect(res.body).toHaveProperty('video');
    });

    it('should return 404 for non-existent listing', async () => {
      const res = await request(app).get('/api/listings/fake-listing-slug');
      expect(res.status).toBe(404);
    });
  });

  // ── GET /api/listings/my ──
  describe('GET /api/listings/my', () => {
    it('should return current user listings', async () => {
      await createSampleListing({ title: 'My Listing 1' });
      await createSampleListing({ title: 'My Listing 2' });

      const res = await request(app)
        .get('/api/listings/my')
        .set('Authorization', `Bearer ${userToken}`);

      expect(res.status).toBe(200);
      const listings = res.body.listings || res.body;
      expect(listings.length).toBe(2);
    });

    it('should not return other users listings', async () => {
      const { user: otherUser } = await createTestUser({ email: 'other@techpulse.com' });
      await createSampleListing({ seller: otherUser._id, title: 'Other Listing' });

      const res = await request(app)
        .get('/api/listings/my')
        .set('Authorization', `Bearer ${userToken}`);

      const listings = res.body.listings || res.body;
      expect(listings.length).toBe(0);
    });

    it('should reject without auth', async () => {
      const res = await request(app).get('/api/listings/my');
      expect(res.status).toBe(401);
    });
  });

  // ── PATCH /api/listings/:id/verify (Admin moderation) ──
  describe('PATCH /api/listings/:id/verify', () => {
    it('should approve a pending listing as admin', async () => {
      const listing = await createSampleListing({ status: 'pending' });

      const res = await request(app)
        .patch(`/api/listings/${listing._id}/verify`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ status: 'active' });

      expect(res.status).toBe(200);
      expect(res.body.status).toBe('active');
    });

    it('should reject a listing with reason', async () => {
      const listing = await createSampleListing({ status: 'pending' });

      const res = await request(app)
        .patch(`/api/listings/${listing._id}/verify`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ status: 'rejected', rejectionReason: 'Vidéo floue, impossible de vérifier.' });

      expect(res.status).toBe(200);
      expect(res.body.status).toBe('rejected');
    });

    it('should reject moderation by regular user', async () => {
      const listing = await createSampleListing({ status: 'pending' });

      const res = await request(app)
        .patch(`/api/listings/${listing._id}/verify`)
        .set('Authorization', `Bearer ${userToken}`)
        .send({ status: 'active' });

      expect(res.status).toBe(403);
    });
  });

  // ── DELETE /api/listings/:id ──
  describe('DELETE /api/listings/:id', () => {
    it('should delete own listing', async () => {
      const listing = await createSampleListing();

      const res = await request(app)
        .delete(`/api/listings/${listing._id}`)
        .set('Authorization', `Bearer ${userToken}`);

      expect(res.status).toBe(200);

      const found = await Listing.findById(listing._id);
      expect(found).toBeNull();
    });

    it('should allow admin to delete any listing', async () => {
      const listing = await createSampleListing();

      const res = await request(app)
        .delete(`/api/listings/${listing._id}`)
        .set('Authorization', `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
    });

    it('should reject delete from non-owner user', async () => {
      const { token: otherToken } = await createTestUser({ email: 'stranger@techpulse.com' });
      const listing = await createSampleListing();

      const res = await request(app)
        .delete(`/api/listings/${listing._id}`)
        .set('Authorization', `Bearer ${otherToken}`);

      expect(res.status).toBe(403);
    });
  });

  // ── Status Workflow ──
  describe('Status Workflow', () => {
    it('should follow pending → active workflow', async () => {
      const listing = await createSampleListing({ status: 'pending' });

      await request(app)
        .patch(`/api/listings/${listing._id}/verify`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ status: 'active' });

      const activated = await Listing.findById(listing._id);
      expect(activated.status).toBe('active');
    });

    it('should follow pending → rejected workflow', async () => {
      const listing = await createSampleListing({ status: 'pending' });

      await request(app)
        .patch(`/api/listings/${listing._id}/verify`)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ status: 'rejected', rejectionReason: 'Photos insuffisantes.' });

      const rejected = await Listing.findById(listing._id);
      expect(rejected.status).toBe('rejected');
    });
  });
});